### ISSUE TITLE
error while loading shared libraries: libboost_system.so.1.58.0

### ISSUE THREAD

**Issue by Kwaskoff** [bettexproject/bettexcoin#1] opened 2018-08-13 17:43 UTC
I try to launch binary and bin ask say: error while loading shared libraries: libboost_system.so.1.58.0
I add lib from http://archive.ubuntu.com/ubuntu/pool/main/b/boost1.58/
and next
and next
next solved "sudo apt install libqrencode3"
But libprotobuf.so.9 is winner =(
Source code not maked too
Help, pls

**Comment by bettexproject** [comment] 2018-08-18 16:56
Sorry for delay. Which OS are you use?

**Comment by rhyslbw** [comment] 2018-12-05 07:32
Same problem here. On Ubuntu 18.10

**Comment by bettexproject** [comment] 2018-12-05 07:54
Hi.
You need to install this library.
Please see https://github.com/bettexproject/bettexcoin/blob/master/doc/build-unix.md

**Comment by rhyslbw** [comment] 2018-12-06 00:39
I'm just trying to run the wallet using released 3.0.0.1 rather than a fresh build. Is it compatible with Ubuntu 18.10?

**Comment by bettexproject** [comment] 2018-12-07 00:11
> I'm just trying to run the wallet using released 3.0.0.1 rather than a fresh build. Is it compatible with Ubuntu 18.10?

the wallet was built and tested on ubuntu 16.04

**Comment by bettexproject** [comment] 2018-12-09 10:49
I close this ticket because the problem is not in the code, but in the installed libraries on the local computer

**Closed as completed by bettexproject** 2018-12-09 10:49 UTC
